<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-165ABPJ" name="com.qa.interestsmart.tests.TC_08_SearchLoan_ByInValidAddress" tests="1" failures="1" timestamp="1 Oct 2020 17:20:47 GMT" time="51.095" errors="0">
  <testcase name="TC_07_SearchLoan_ByInValidAddress" time="51.095" classname="com.qa.interestsmart.tests.TC_08_SearchLoan_ByInValidAddress">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [We found your mortgage data!] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [We found your mortgage data!] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.qa.interestsmart.pages.SignInToApplication.checkLoanByEnteringAddress(SignInToApplication.java:481)
	at com.qa.interestsmart.tests.TC_08_SearchLoan_ByInValidAddress.TC_07_SearchLoan_ByInValidAddress(TC_08_SearchLoan_ByInValidAddress.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- TC_07_SearchLoan_ByInValidAddress -->
</testsuite> <!-- com.qa.interestsmart.tests.TC_08_SearchLoan_ByInValidAddress -->
